version: 2
jobs:
  setup:
    docker:
      - image: circleci/node:10.15.3
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Setup Service Account
          command: echo ${CLIENT_SECRET} | base64 -d > $HOME/client-secret.json
      - run:
          name: Docker Login
          command: docker login -u _json_key -p "$(cat ${HOME}/client-secret.json)" https://gcr.io
      - persist_to_workspace:
          root: ./
          paths:
            - .
      # - run:
      #     name: Install Pub/Sub Emulator
      #     command: gcloud --quiet components install pubsub-emulator
      # - run:
      #     name: Update components
      #     command: gcloud --quiet components update
  build:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - attach_workspace:
            at: ./
      - run:
          name: Build
          command: npm run only:build
      - persist_to_workspace:
          root: ./
          paths:
            - dist
  lint:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Lint
          command: npm run lint -- --format junit --output-file ./reports/eslint/results.xml
      - store_test_results:
          path: ./reports
      - store_artifacts:
          path: ./reports
  test:
    docker:
      - image: circleci/node:10.15.3
        environment:
          MOCHA_OPTS: --reporter mocha-junit-reporter --reporter-options mochaFile=./reports/junit/mocha/mocha.xml
      - image: singularities/pubsub-emulator
        environment:
          PUBSUB_PROJECT_ID: pubcap-test
          PUBSUB_LISTEN_ADDRESS: 0.0.0.0:8085
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Unit Tests
          command: npm run only:test
      # - run:
      #     name: Coverage
      #     command: npm run only:lCov
      # - run:
      #     name: Upload to codecov
      #     command: npm run ci:codecov
      - store_test_results:
          path: ./reports
      - store_artifacts:
          path: ./reports
  publish:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Setup NPM auth token
          command: npm config set //registry.npmjs.org/:_authToken "${NPM_TOKEN}"
      - run:
          name: Publish
          command: ./scripts/release.sh
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - setup
      - build:
          context: 6rs-public-npm
          requires:
            - setup
      - lint:
          context: 6rs-public-npm
          requires:
            - setup
      - test:
          context: 6rs-public-npm
          requires:
            - setup
      - publish:
          context: 6rs-public-npm
          requires:
            - setup
            - build
            - lint
            - test
          filters:
            branches:
              only: master
